Repository woowa-techcamp-2022/android-repo-07, pull requests merged in 2022-07, with the labels that each got.

#5 [CHORE] 프로젝트 색상 및 Shape 추가
  app/src/main/res/drawable/bg_black.xml
  app/src/main/res/drawable/bg_main_tab.xml
  app/src/main/res/drawable/rectangle_navy_radius_14.xml
  app/src/main/res/drawable/rectangle_primary_radius_14.xml
  app/src/main/res/values/colors.xml
Labels: 광민, Done, Review Required

#9 [ADD] #8 로그인 화면 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/woowatechcamp/githubapplication/GithubApplication.kt
  app/src/main/java/org/woowatechcamp/githubapplication/di/NetworkModule.kt
  app/src/main/java/org/woowatechcamp/githubapplication/di/PreferencesModule.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/AuthPreferences.kt
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: 광민, Done, Review Required

#14 [FEAT] Issue 데이터 연동 로직 처리 코드입니다
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/IssueRepository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/IssueService.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/model/Assignee.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/model/IssueResponse.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/model/IssueResponseItem.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/model/Label.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/model/Owner.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/model/Permissions.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/model/PullRequest.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/model/Reactions.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/model/Repository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/model/User.kt
  app/src/main/java/org/woowatechcamp/githubapplication/di/NetworkModule.kt
  app/src/main/java/org/woowatechcamp/githubapplication/network/TokenInterceptor.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/MainViewModel.kt
Labels: 광민, Done, Review Required

#15 [UI] Search 뷰 레이아웃 짜기
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/woowatechcamp/githubapplication/GithubApplication.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/search/SearchActivity.kt
  app/src/main/res/drawable/ic_star_24.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_search.xml
  app/src/main/res/layout/layout_search_edit.xml
  app/src/main/res/layout/layout_search_empty.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 다빈, Done, Review Required

#25 [FEAT] Notifications 로직 구현
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/NotiRepository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/NotiService.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/model/NotiMarkResponse.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/model/NotiResponse.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/model/NotiResponseItem.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/model/Owner.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/model/Repository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/model/Subject.kt
  app/src/main/java/org/woowatechcamp/githubapplication/di/NetworkModule.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/MainViewModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/issue/IssueFragment.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/notifications/NotiViewModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/notifications/NotificationsFragment.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/notifications/adapter/NotiAdapter.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/view_util/SwipeCallback.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/view_util/SwipeListener.kt
Labels: 광민, Done, Review Required

#35 [CHORE] 머지 후 빌드 테스트
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/MainActivity.kt
Labels: 다빈, 광민, Done

#40 [FEAT] 서치 뷰 서버통신
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/woowatechcamp/githubapplication/data/remote/dto/ResponseRepoSearchDTO.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/remote/paging/RepoPagingSource.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/remote/service/SearchService.kt
  app/src/main/java/org/woowatechcamp/githubapplication/di/NetworkModule.kt
  app/src/main/java/org/woowatechcamp/githubapplication/domain/entity/SearchInfo.kt
  app/src/main/java/org/woowatechcamp/githubapplication/domain/usecase/RepoSearchUseCase.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/search/SearchActivity.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/search/SearchAdapter.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/search/SearchViewModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/search/custom/SearchEditText.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/Debounce.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/OffsetPagingSource.kt
  app/src/main/res/drawable/ic_star_border_24.xml
  app/src/main/res/drawable/rectangle_fill_navy_radius_7.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_search.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 다빈, Review Required

#39 [REFACTOR] 메인화면 뷰 및 로직 수정
  app/src/main/java/org/woowatechcamp/githubapplication/GithubApplication.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/NotiRepository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/NotiService.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/model/NotiResponse.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/model/NotiResponseItem.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/UserRepository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/UserService.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/entity/UserResponse.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/starred/License.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/starred/Owner.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/starred/StarredResponse.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/starred/StarredResponseItem.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/MainActivity.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/MainViewModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/issue/adapter/IssueAdapter.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/notifications/NotiViewModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/notifications/NotificationsFragment.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/notifications/adapter/NotiAdapter.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/notifications/model/NotiModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/profile/ProfileActivity.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/search/SearchViewModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/user/model/UserModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/ext/StringExt.kt
  app/src/main/res/drawable/bg_main_tab.xml
  app/src/main/res/drawable/tab_main_selected.xml
  app/src/main/res/drawable/tab_main_unselected.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/item_noti.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: enhancement, 광민, Done

#44 [FEAT] Notifications 에서 Comment 개수 가져오는 로직 구현
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/IssueService.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/model/IssueResponse.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/model/IssueResponseItem.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/NotiService.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/model/NotiResponse.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/model/NotiResponseItem.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/UserService.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/comment/CommentRespose.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/comment/Reactions.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/comment/User.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/starred/StarredResponse.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/starred/StarredResponseItem.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/issue/IssueViewModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/issue/adapter/IssueAdapter.kt
Labels: Done, Review Required

#48 [REFACTOR] SignIn 로그인 로직 변경
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/woowatechcamp/githubapplication/data/auth/AuthRepository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/auth/AuthResponse.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/auth/AuthService.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/auth/SignInActivity.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/auth/SignInViewModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/search/SearchAdapter.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/UiState.kt
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, 광민, Done, Review Required

#50 [REFACTOR] Notifications 화면 로직 변경
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/NotiRepository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/NotiService.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/notifications/NotiViewModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/notifications/NotificationsFragment.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/notifications/model/NotiModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/SwipeCallback.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/ext/DateExt.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/ext/LongExt.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/ext/StringExt.kt
Labels: enhancement, 광민, Done

#54 [REFACTOR] notifications api 비동기적으로 리팩토링
  app/src/main/java/org/woowatechcamp/githubapplication/data/auth/AuthRepository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/auth/AuthResponse.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/auth/AuthService.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/IssueCategory.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/IssueRepository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/IssueService.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/model/IssueResponse.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/NotiRepository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/NotiService.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/model/NotiMarkResponse.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/remote/paging/RepoPagingSource.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/UserRepository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/UserService.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/comment/CommentResponse.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/comment/Reactions.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/entity/UserResponse.kt
  app/src/main/java/org/woowatechcamp/githubapplication/di/NetworkModule.kt
  app/src/main/java/org/woowatechcamp/githubapplication/di/PreferencesModule.kt
  app/src/main/java/org/woowatechcamp/githubapplication/domain/usecase/RepoSearchUseCase.kt
  app/src/main/java/org/woowatechcamp/githubapplication/network/TokenInterceptor.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/adapter/ViewPagerAdapter.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/auth/SignInActivity.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/auth/SignInViewModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/MainActivity.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/MainViewModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/issue/IssueFragment.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/issue/IssueViewModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/issue/adapter/IssueAdapter.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/issue/adapter/IssueSpinAdapter.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/issue/model/IssueModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/notifications/NotiViewModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/notifications/NotificationsFragment.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/notifications/adapter/NotiAdapter.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/notifications/model/NotiModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/profile/ProfileActivity.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/search/SearchAdapter.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/search/SearchViewModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/user/model/UserModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/AuthPreferences.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/ResolutionMetrics.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/SnackBarUtil.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/SwipeCallback.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/SwipeListener.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/UiState.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/ext/DateExt.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/ext/IntExt.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/ext/StringExt.kt
  app/src/main/res/drawable/rectangle_grey_radius_3.xml
  app/src/main/res/layout/item_noti.xml
Labels: enhancement, 광민, Done

#59 [REFACTOR] 메인화면 로직 수정
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/UserRepository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/entity/UserResponse.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/MainActivity.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/MainViewModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/profile/ProfileActivity.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/ext/ImgExt.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: enhancement, Review Required

#61 [REFACTOR] repository 에서 viewmodel 로 데이터 로직 이전
  app/src/main/java/org/woowatechcamp/githubapplication/data/auth/AuthRepository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/IssueRepository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/model/IssueResponse.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/NotiRepository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/model/NotiResponse.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/UserRepository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/auth/SignInViewModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/issue/IssueFragment.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/issue/IssueViewModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/notifications/NotiViewModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/notifications/adapter/NotiAdapter.kt
  app/src/main/res/layout/item_issue.xml
Labels: bug, enhancement, Review Required

#63 Refactor/code review
  app/src/main/java/org/woowatechcamp/githubapplication/data/auth/AuthRepository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/auth/AuthService.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/IssueRepository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/IssueService.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/NotiRepository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/NotiService.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/UserRepository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/UserService.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/adapter/ViewPagerAdapter.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/auth/SignInActivity.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/MainActivity.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/MainViewModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/issue/IssueFragment.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/issue/adapter/IssueAdapter.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/issue/adapter/IssueSpinAdapter.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/notifications/NotificationsFragment.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/notifications/adapter/NotiAdapter.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/SwipeCallback.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/UiState.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/ext/ContextExt.kt
Labels: enhancement, 광민, Review Required

#64 [FEAT] 서치뷰 페이징 적용
  app/src/main/java/org/woowatechcamp/githubapplication/data/remote/paging/RepoPagingSource.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/search/SearchActivity.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/search/SearchAdapter.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/search/SearchViewModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/Debounce.kt
  app/src/main/res/layout/activity_search.xml
Labels: 다빈, Done

#65 [FEAT] Profile 뷰 암시적 인텐트 적용
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/entity/UserResponse.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/profile/ProfileActivity.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/user/model/UserModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/BindingAdapter.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/ext/ContextExt.kt
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/item_search.xml
Labels: 다빈, Done

#69 [REFACTOR] #68 - 네이밍 수정
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/IssueRepository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/model/Assignee.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/model/IssueResponse.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/model/Label.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/model/Owner.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/model/PullRequest.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/model/Reactions.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/model/Repository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/model/User.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/model/NotiResponse.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/model/Owner.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/model/Repository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/model/Subject.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/comment/CommentResponse.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/comment/Reactions.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/comment/User.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/entity/Plan.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/entity/UserResponse.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/starred/License.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/starred/Owner.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/starred/StarredResponse.kt
Labels: 광민, Done, Review Required

#71 [FEAT] test code 추가
  app/build.gradle.kts
  app/src/main/java/org/woowatechcamp/githubapplication/data/auth/AuthRepository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/auth/AuthRepositoryImpl.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/IssueRepository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/issue/IssueRepositoryImpl.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/NotiRepository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/noti/NotiRepositoryImpl.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/UserRepository.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/user/UserRepositoryImpl.kt
  app/src/main/java/org/woowatechcamp/githubapplication/di/NetworkModule.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/MainViewModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/home/notifications/NotiViewModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/search/SearchViewModel.kt
  app/src/test/java/org/woowatechcamp/githubapplication/ExampleUnitTest.kt
  app/src/test/java/org/woowatechcamp/githubapplication/auth/FakeAuthRepository.kt
  app/src/test/java/org/woowatechcamp/githubapplication/auth/TestAuthViewModel.kt
  app/src/test/java/org/woowatechcamp/githubapplication/issue/FakeIssueRepository.kt
  app/src/test/java/org/woowatechcamp/githubapplication/issue/TestIssueViewModel.kt
  app/src/test/java/org/woowatechcamp/githubapplication/notification/FakeNotiRepository.kt
  app/src/test/java/org/woowatechcamp/githubapplication/notification/TestNotiViewModel.kt
  app/src/test/java/org/woowatechcamp/githubapplication/rule/InstantTaskExecutorRule.kt
  app/src/test/java/org/woowatechcamp/githubapplication/rule/MainCoroutineRule.kt
  app/src/test/java/org/woowatechcamp/githubapplication/user/FakeMainRepository.kt
  app/src/test/java/org/woowatechcamp/githubapplication/user/TestMainViewModel.kt
  gradle/libs.versions.toml
Labels: bug, enhancement, Review Required

#78 [REFACTOR] 서치뷰, 프로필 뷰 리뷰 반영 및 성능 개선
  app/src/main/assets/colors.json
  app/src/main/java/org/woowatechcamp/githubapplication/data/remote/dto/ResponseRepoSearchDTO.kt
  app/src/main/java/org/woowatechcamp/githubapplication/data/remote/paging/RepoPagingSource.kt
  app/src/main/java/org/woowatechcamp/githubapplication/domain/entity/SearchInfo.kt
  app/src/main/java/org/woowatechcamp/githubapplication/domain/usecase/RepoSearchUseCase.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/search/SearchActivity.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/search/SearchAdapter.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/search/SearchViewModel.kt
  app/src/main/java/org/woowatechcamp/githubapplication/presentation/search/custom/SearchEditText.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/JsonToColorUtil.kt
  app/src/main/java/org/woowatechcamp/githubapplication/util/OffsetPagingSource.kt
  app/src/main/res/layout/item_search.xml
Labels: 다빈, Done

#86 [REFACTOR] #85 - 테스트 코드 단위별로 분리
  app/src/test/java/org/woowatechcamp/githubapplication/auth/TestAuthViewModel.kt
  app/src/test/java/org/woowatechcamp/githubapplication/issue/TestIssueViewModel.kt
  app/src/test/java/org/woowatechcamp/githubapplication/notification/TestNotiViewModel.kt
  app/src/test/java/org/woowatechcamp/githubapplication/user/TestMainViewModel.kt
Labels: enhancement, 광민, Done
